IF(WIN32)
  SET(ASSUMED_DESTINATION_PREFIX "${${PROJECT_NAME}_SOURCE_DIR}/")
ELSE()
  SET(ASSUMED_DESTINATION_PREFIX "")
ENDIF()

# Install the libraries.
FOREACH(LIBRARY_NAME ${LIBRARY_NAMES})
  IF(NOT ${LIBRARY_NAME}_IS_TEMPLATE_LIBRARY)
    INSTALL(TARGETS ${LIBRARY_NAME}
      RUNTIME DESTINATION "${ASSUMED_DESTINATION_PREFIX}bin"
      LIBRARY DESTINATION "${ASSUMED_DESTINATION_PREFIX}lib"
      ARCHIVE DESTINATION "${ASSUMED_DESTINATION_PREFIX}lib")
  ENDIF()
ENDFOREACH()