# Help outside projects build this library.
INCLUDE(CMakeExportBuildSettings)
EXPORT_LIBRARY_DEPENDENCIES(${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}LibraryDepends.cmake)
CMAKE_EXPORT_BUILD_SETTINGS(${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}BuildSettings.cmake)


# Write ${PROJECT_NAME}Config.cmake file.
# CV_ prefixed variables are only used inside ${PROJECT_NAME}Config.cmake for replacement
# during the following CONFIGURE_FILE call.
SET(CV_CONFIG_TO_ROOT ".")
SET(CV_LIBRARY_DEPENDS_FILE "${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}LibraryDepends.cmake")
SET(CV_BUILD_SETTINGS_FILE "${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}BuildSettings.cmake")

SET(CV_INCLUDE_DIRS "${${PROJECT_NAME}_SOURCE_DIR}/include")
SET(CV_LIBRARY_DIRS "${${PROJECT_NAME}_SOURCE_DIR}/lib")

SET(CV_EXTRA_INCLUDE_DIRS ${EXTRA_INCLUDE_DIRS})
SET(CV_EXTRA_LIBRARY_DIRS ${EXTRA_LIBRARY_DIRS})

SET(CV_USE_FILES_PATH "${${PROJECT_NAME}_BINARY_DIR}")
SET(CV_LIBRARY_NAMES ${LIBRARY_NAMES})

CONFIGURE_FILE(
  "${${PROJECT_NAME}_SOURCE_DIR}/../CMakeTemplateConfig.cmake"
  "${${PROJECT_NAME}_BINARY_DIR}/${PROJECT_NAME}Config.cmake" @ONLY IMMEDIATE)

 
# Write ${LIBRARY_NAME}Use.cmake file.
# UV_ prefixed variables are only used inside ${LIBRARY_NAME}Use.cmake for replacement
# during the following CONFIGURE_FILE call.
FOREACH(LIBRARY_NAME ${LIBRARY_NAMES})
  SET(UV_LIBRARY_NAME ${LIBRARY_NAME})
  
  IF(${LIBRARY_NAME}_IS_TEMPLATE_LIBRARY)
    SET(UV_IS_NOT_TEMPLATE_LIBRARY 0)
  ELSE()
    SET(UV_IS_NOT_TEMPLATE_LIBRARY 1)
  ENDIF()

  CONFIGURE_FILE(
    "${${PROJECT_NAME}_SOURCE_DIR}/../CMakeTemplateUse.cmake"
    "${${PROJECT_NAME}_BINARY_DIR}/${LIBRARY_NAME}Use.cmake" @ONLY IMMEDIATE)
ENDFOREACH()