result_of::make_weighted_scalar_c<0>::type zero;
result_of::make_weighted_scalar_c<1>::type one;

#define _GA_DECLARE_CONSTANT_BASIS_VECTOR(Index) \
	ga::result_of::make_basis_vector_c<Index>::type e##Index; \

#if GA_MAX_NDIMS >= 1
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(0)
#endif

#if GA_MAX_NDIMS >= 2
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(1)
#endif

#if GA_MAX_NDIMS >= 3
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(2)
#endif

#if GA_MAX_NDIMS >= 4
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(3)
#endif

#if GA_MAX_NDIMS >= 5
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(4)
#endif

#if GA_MAX_NDIMS >= 6
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(5)
#endif

#if GA_MAX_NDIMS >= 7
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(6)
#endif

#if GA_MAX_NDIMS >= 8
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(7)
#endif

#if GA_MAX_NDIMS >= 9
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(8)
#endif

#if GA_MAX_NDIMS >= 10
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(9)
#endif

#if GA_MAX_NDIMS >= 11
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(10)
#endif

#if GA_MAX_NDIMS >= 12
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(11)
#endif

#if GA_MAX_NDIMS >= 13
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(12)
#endif

#if GA_MAX_NDIMS >= 14
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(13)
#endif

#if GA_MAX_NDIMS >= 15
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(14)
#endif

#if GA_MAX_NDIMS >= 16
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(15)
#endif

#if GA_MAX_NDIMS >= 17
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(16)
#endif

#if GA_MAX_NDIMS >= 18
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(17)
#endif

#if GA_MAX_NDIMS >= 19
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(18)
#endif

#if GA_MAX_NDIMS >= 20
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(19)
#endif

#if GA_MAX_NDIMS >= 21
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(20)
#endif

#if GA_MAX_NDIMS >= 22
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(21)
#endif

#if GA_MAX_NDIMS >= 23
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(22)
#endif

#if GA_MAX_NDIMS >= 24
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(23)
#endif

#if GA_MAX_NDIMS >= 25
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(24)
#endif

#if GA_MAX_NDIMS >= 26
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(25)
#endif

#if GA_MAX_NDIMS >= 27
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(26)
#endif

#if GA_MAX_NDIMS >= 28
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(27)
#endif

#if GA_MAX_NDIMS >= 29
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(28)
#endif

#if GA_MAX_NDIMS >= 30
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(29)
#endif

#if GA_MAX_NDIMS >= 31
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(30)
#endif

#if GA_MAX_NDIMS >= 32
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(31)
#endif

#if GA_MAX_NDIMS >= 33
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(32)
#endif

#if GA_MAX_NDIMS >= 34
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(33)
#endif

#if GA_MAX_NDIMS >= 35
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(34)
#endif

#if GA_MAX_NDIMS >= 36
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(35)
#endif

#if GA_MAX_NDIMS >= 37
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(36)
#endif

#if GA_MAX_NDIMS >= 38
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(37)
#endif

#if GA_MAX_NDIMS >= 39
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(38)
#endif

#if GA_MAX_NDIMS >= 40
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(39)
#endif

#if GA_MAX_NDIMS >= 41
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(40)
#endif

#if GA_MAX_NDIMS >= 42
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(41)
#endif

#if GA_MAX_NDIMS >= 43
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(42)
#endif

#if GA_MAX_NDIMS >= 44
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(43)
#endif

#if GA_MAX_NDIMS >= 45
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(44)
#endif

#if GA_MAX_NDIMS >= 46
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(45)
#endif

#if GA_MAX_NDIMS >= 47
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(46)
#endif

#if GA_MAX_NDIMS >= 48
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(47)
#endif

#if GA_MAX_NDIMS >= 49
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(48)
#endif

#if GA_MAX_NDIMS >= 50
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(49)
#endif

#if GA_MAX_NDIMS >= 51
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(50)
#endif

#if GA_MAX_NDIMS >= 52
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(51)
#endif

#if GA_MAX_NDIMS >= 53
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(52)
#endif

#if GA_MAX_NDIMS >= 54
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(53)
#endif

#if GA_MAX_NDIMS >= 55
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(54)
#endif

#if GA_MAX_NDIMS >= 56
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(55)
#endif

#if GA_MAX_NDIMS >= 57
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(56)
#endif

#if GA_MAX_NDIMS >= 58
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(57)
#endif

#if GA_MAX_NDIMS >= 59
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(58)
#endif

#if GA_MAX_NDIMS >= 60
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(59)
#endif

#if GA_MAX_NDIMS >= 61
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(60)
#endif

#if GA_MAX_NDIMS >= 62
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(61)
#endif

#if GA_MAX_NDIMS >= 63
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(62)
#endif

#if GA_MAX_NDIMS >= 64
	_GA_DECLARE_CONSTANT_BASIS_VECTOR(63)
#endif
